framework:
    default_locale: '%env(DEFAULT_LOCALE)%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - '%env(FALLBACK_LOCALE)%'
        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
             loco:
                 dsn: '%env(LOCO_DSN)%'
                 domains: [ 'messages' ]
                 locales: [ 'fr-FR' ]
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
#            phrase:
#                dsn: '%env(PHRASE_DSN)%'
